### ISSUE TITLE
vant的shownotify等css风格丢失

### ISSUE THREAD

**Issue by ebolavirus** [qmcx-ming/vue3-vant-template#2]
基于代码加了vant的showNotify等指令，vant的notify弹出框是空白的背景，好像相关的css样式丢失了

**Comment by qmcxming** [comment]
你是不是在页面多导入了
import { showNotify } from 'vant';

**Comment by qmcxming** [comment]
vant配置了自动导入，不需要再导入vant的

**Comment by qmcxming** [comment]
![image](https://github.com/user-attachments/assets/71261add-d8ba-4ece-bc47-583b26301500)

**Comment by ebolavirus** [comment]
是的，感谢解惑 :)
